version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - dotnet
    commit-message:
      prefix: "chore"
    groups:
      nuget:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - javascript
    commit-message:
      prefix: "chore"
    groups:
      npm:
        patterns:
          - "*"
