using System.Globalization;
using System.Text;
using Dbhq.Cpu6502.Bench;

namespace Dbhq.Cpu6502.ChipTrace;

/// <summary>
/// Runs the speed check's program on the core and records every bus cycle, so
/// the site's chip page can replay what the core did. Nothing on that page is
/// animated by hand: every lit address line, data line and register is a value
/// this file recorded.
/// </summary>
public static class ChipTrace
{
    /// <summary>Where the committed file lives, from the repository root.</summary>
    public const string RelativePath = "site/src/data/chip-trace.json";

    /// <summary>The program's loop starts here; the trace ends the time it gets back here after <see cref="Laps"/> laps.</summary>
    private const ushort Loop = 0x1FE2;

    /// <summary>How many times round the loop the trace records.</summary>
    public const int Laps = 8;

    private sealed class RecordingBus : IBus
    {
        public readonly byte[] Memory = new byte[0x10000];
        public readonly List<(ushort Address, byte Data, bool Write)> Cycles = [];

        public byte Read(ushort address)
        {
            byte value = Memory[address];
            Cycles.Add((address, value, false));
            return value;
        }

        public void Write(ushort address, byte value)
        {
            Memory[address] = value;
            Cycles.Add((address, value, true));
        }
    }

    /// <summary>The trace as the text of the committed file. The same input always gives the same bytes.</summary>
    public static string Build()
    {
        var bus = new RecordingBus();
        Workload.Bytes.CopyTo(bus.Memory.AsSpan(Workload.ProgramStart));
        var cpu = new Cpu(bus, CpuVariant.Nmos6502) { PC = Workload.ProgramStart, S = 0xFF, P = 0x24 };

        var text = new StringBuilder();
        string I(long n) => n.ToString(CultureInfo.InvariantCulture);
        string Regs() => $"[{cpu.A},{cpu.X},{cpu.Y},{cpu.S},{cpu.P}]";

        text.Append("{\n");
        text.Append("\"about\": \"Generated by tools/Dbhq.Cpu6502.ChipTrace from the speed check's program (bench/Dbhq.Cpu6502.WasmBench/Workload.cs) on the NMOS 6502. Do not edit by hand: run the tool, and the test ChipTraceTests fails if this file and the tool disagree.\",\n");
        text.Append("\"variant\": \"Nmos6502\",\n");
        text.Append($"\"laps\": {I(Laps)},\n");
        text.Append($"\"start\": {{\"pc\": {I(cpu.PC)}, \"regs\": {Regs()}}},\n");
        text.Append("\"instructions\": [\n");

        int laps = 0;
        bool first = true;
        while (true)
        {
            TraceLine line = Tracer.Capture(cpu, a => bus.Memory[a]);
            int from = bus.Cycles.Count;
            cpu.Step();
            int count = bus.Cycles.Count - from;
            if (!first)
            {
                text.Append(",\n");
            }

            first = false;
            text.Append($"{{\"pc\": {I(line.PC)}, \"text\": \"{line.Text}\", \"mnemonic\": \"{line.Opcode.Mnemonic}\", \"mode\": \"{line.Opcode.Mode}\", \"first\": {I(from)}, \"cycles\": {I(count)}, \"after\": {Regs()}}}");
            if (cpu.PC == Loop && ++laps == Laps)
            {
                break;
            }
        }

        text.Append("\n],\n");
        text.Append("\"cycles\": [\n");
        for (int i = 0; i < bus.Cycles.Count; i++)
        {
            var (address, data, write) = bus.Cycles[i];
            text.Append($"[{I(address)},{I(data)},{(write ? 1 : 0)}]");
            text.Append(i + 1 < bus.Cycles.Count ? ",\n" : "\n");
        }

        text.Append("]\n}\n");
        return text.ToString();
    }
}
