<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Dbhq.Machines.BbcMicro/Dbhq.Machines.BbcMicro.csproj" />
    <ProjectReference Include="../../../tests/Dbhq.Cpu6502.TestSupport/Dbhq.Cpu6502.TestSupport.csproj" />
  </ItemGroup>
</Project>
