#!/usr/bin/env bash
# Regenerates the interrupt tests' expected data from perfect6502, a
# simulation of the real 6502's transistors, at a pinned commit.
#
#   tools/perfect6502/generate.sh
#
# Needs git and a C compiler. Writes
# tests/Dbhq.Cpu6502.Tests/Interrupts/visual6502.txt.
set -euo pipefail

commit=09fc542877a84318291aa42dab143a3e2c3db974
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
work="$root/.testdata/perfect6502"
out="$root/tests/Dbhq.Cpu6502.Tests/Interrupts/visual6502.txt"

if [ ! -d "$work/.git" ]; then
    git clone --quiet https://github.com/dbhq-uk/perfect6502.git "$work"
fi
git -C "$work" fetch --quiet origin "$commit"
git -C "$work" checkout --quiet "$commit"
[ "$(git -C "$work" rev-parse HEAD)" = "$commit" ] || { echo "perfect6502 is not at $commit" >&2; exit 1; }

cc -O2 -I"$work" -o "$work/harness" "$here/harness.c" "$work/perfect6502.c" "$work/netlist_sim.c"
mkdir -p "$(dirname "$out")"
{
    echo "# Generated by tools/perfect6502/generate.sh from mist64/perfect6502 at $commit."
    echo "# Do not edit by hand. Each section is one run: the program, the cycles at"
    echo "# which the IRQ and NMI lines go active and inactive, the registers at the"
    echo "# first opcode fetch from \$0400, then one line per cycle: index, address,"
    echo "# data, R or W."
    "$work/harness"
} > "$out"
echo "$(grep -c '^## ' "$out") runs written to $out"
